---
# tasks file for ansible-role-awscli

- name: 'Link to /usr/local/sbin'
  file:
    src:   '/usr/bin/aws'
    dest:  '/usr/local/sbin/aws'
    state: 'link'

- name: 'Link to /usr/local/sbin'
  file:
    src:   '/usr/bin/aws'
    dest:  '/usr/local/bin/aws'
    state: 'link'