---
# tasks file for ansible-role-awscli

- name: 'Install python-virtualenv'
  package:
    name:  'python-virtualenv'
    state: 'present'

- name: 'Create directory for venv'
  file:
    path:  '{{ venv_dir }}'
    owner: 'root'
    group: 'root'
    mode:  0755
    state: 'directory'

- name: 'Install awscli through PIP in virtualenv'
  pip:
    name:       'awscli'
    virtualenv: '{{ venv_dir }}/aws'
    version:    '{{ rhcentos_awscli_version | default(omit) }}'

- name: 'Copy wrapper'
  template:
    src:  'aws.j2'
    dest: '/usr/local/bin/aws'
    mode: 0555

- name: 'Link to /usr/local/sbin'
  file:
    src:   '/usr/local/bin/aws'
    dest:  '/usr/local/sbin/aws'
    state: 'link'
