---
# tasks file for ansible-role-awscli

- name: 'Verify that we are on supported distribution'
  assert:
    that: |
      (
        (ansible_distribution == 'RedHat') and (ansible_distribution_major_version is version_compare('7', '=='))
      ) or (
        (ansible_distribution == 'CentOS') and (ansible_distribution_major_version is version_compare('7', '=='))
      ) or (
        (ansible_distribution == "Amazon")
      )

- name: 'Installation for RHEL/CentOS'
  include_tasks: 'install-rhcentos.yml'
  when: (ansible_distribution == 'RedHat') or (ansible_distribution == 'CentOS')

- name: 'Installation for Amazon Linux'
  include_tasks: 'install-amazon.yml'
  when: ansible_distribution == 'Amazon'